## First Question

In [1]:
import numpy as np

#create your first matrix

lst= [ ] 
n = int(input("Enter number of elements : ")) 
  
for i in range(0,n):
    g = [float(input()), float(input())]
    lst.append(g)
      
print(lst)

a = np.array(lst)

#create your second matrix

lst2= [ ] 
n = int(input("Enter number of elements : ")) 
  
for i in range(0,n):
    g = [float(input()), float(input())]
    lst2.append(g)
    
print(lst2)

b = np.array(lst2)


print("Our values and their dot product:" )
print(a, b, np.dot(a, b), sep = ',     ')

Enter number of elements : 2
1
2
3
4
[[1.0, 2.0], [3.0, 4.0]]
Enter number of elements : 2
3
4
5
6
[[3.0, 4.0], [5.0, 6.0]]
Our values and their dot product:
[[1. 2.]
 [3. 4.]],     [[3. 4.]
 [5. 6.]],     [[13. 16.]
 [29. 36.]]


## Second Question

Inner matrix is what we know as dot product but what exactly is the outer product?

suppose you have u =<u1, u2, u3>, v =<v1, v2, v3> dot product of these two would be $  u^T   v$

but you might not know is outer product of these two would be $ u    v^T = <[u1*v1,u1*v2,u1*v3];[u2*v1,u2*v2,u2*v3];[u3*v1,u3*v2,u3*v3]> $

In [6]:
import numpy as np
#çalınan kodların kaynağı:

#https://www.quora.com/What-does-the-following-line-mean-in-Python-list-map-int-input-strip-split-I
#https://www.geeksforgeeks.org/take-matrix-input-from-user-in-python/
  
R1 = int(input("Enter the number of rows:"))
C1 = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries1 = list(map(int, input().split()))

matrix1 = np.array(entries1).reshape(R1, C1)

R2 = int(input("Enter the number of rows:"))
C2 = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries2 = list(map(int, input().split()))

matrix2 = np.array(entries2).reshape(R2, C2)
  
# For printing the matrix
print("Our values and their outer product:")

print(matrix1, matrix2, np.outer(matrix, matrix2), sep = ', ')

Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
1 2 3 4
Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
1 2 3 4
Our values and their outer product:
[[1 2]
 [3 4]], [[1 2]
 [3 4]], [[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


## Third Question

In [7]:
R3 = int(input("Enter the number of rows:"))
C3 = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries3 = list(map(int, input().split()))
  

matrix3 = np.array(entries3).reshape(R3, C3)



R4 = int(input("Enter the number of rows:"))
C4 = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries4 = list(map(int, input().split()))

matrix4 = np.array(entries4).reshape(R4, C4)
  


print("our values and their cross product:")

print(matrix3, matrix4, np.cross(matrix3, matrix4), sep = ', ')

Enter the number of rows:1
Enter the number of columns:3
Enter the entries in a single line (separated by space): 
1 2 3
Enter the number of rows:1
Enter the number of columns:3
Enter the entries in a single line (separated by space): 
1 2 3
our values and their cross product:
[[1 2 3]], [[1 2 3]], [[0 0 0]]


## Fourth Question


In [8]:
R5 = int(input("Enter the number of rows:"))
C5 = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries5 = list(map(int, input().split()))
  
# For printing the matrix
matrix5 = np.array(entries).reshape(R5, C5)

matrix5_det = np.linalg.det(matrix5)
print("our values and it's cross product:")

print(matrix5, matrix5_det, sep = ', ')

Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
1 2 3 4
our values and it's cross product:
[[1 2]
 [3 4]], -2.0000000000000004


## Fifth Question


In [30]:
#Einstein's summation convention'ın ne olduğunu anlayamadım

## Sixth Question

In [31]:
R6 = int(input("Enter the number of rows:"))
C6 = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries6 = list(map(int, input().split()))
  
# For printing the matrix
matrix6 = np.array(entries).reshape(R6, C6)


R7 = int(input("Enter the number of rows:"))
C7 = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries7 = list(map(int, input().split()))
  
# For printing the matrix
matrix7 = np.array(entries7).reshape(R7, C7)


print(matrix5, matrix6, np.inner(matrix5, matrix6), sep = 'oooooooooo')





Enter the number of rows:2
Enter the number of columns:3
Enter the entries in a single line (separated by space): 
1 2 3 4 5 6
Enter the number of rows:2
Enter the number of columns:3
Enter the entries in a single line (separated by space): 
7 8 9 10 11 12
[[1 2 3]
 [4 5 6]]oooooooooo[[ 7  8  9]
 [10 11 12]]oooooooooo[[ 50  68]
 [122 167]]


## Seventh Question


In [9]:
D = np.array([[4, 2, 2],[2, 4, 2],[2, 2, 4]])

w, v =np.linalg.eig(D)

print("our eigen values (as an array) and eigen vector:")

print(w, v, sep = ', ')



our eigen values (as an array) and eigen vector:
[2. 8. 2.], [[-0.81649658  0.57735027 -0.32444284]
 [ 0.40824829  0.57735027 -0.48666426]
 [ 0.40824829  0.57735027  0.81110711]]


## Eighth Question

Kronecker Product = For example you have two matrices A and B, kronecker product of these two is a vector like; <<a_11*B>,...<a_nn*B>> assuming A is n*n

https://en.wikipedia.org/wiki/Kronecker_product

In [43]:
R8 = int(input("Enter the number of rows:"))
C 8= int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries8 = list(map(int, input().split()))
  
# For printing the matrix
matrix8 = np.array(entries8).reshape(R8, C8)


R9 = int(input("Enter the number of rows:"))
C9 = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries9 = list(map(int, input().split()))
  
# For printing the matrix
matrix9 = np.array(entries9).reshape(R9, C9)

print("our values and it's kronecker product:")

print(matrix8, matrix9, np.kron(matrix8, matrix9), sep = ', ')


Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
1 5 7 11
Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
11 5 77 11
[[ 1  5]
 [ 7 11]]ğğğğğğğğğ[[11  5]
 [77 11]]ğğğğğğğğğ[[ 11   5  55  25]
 [ 77  11 385  55]
 [ 77  35 121  55]
 [539  77 847 121]]


## Ninth Question

condition number is defined as $ k = ||A||||A^{-1}||$ so obviously A must be a square matrix

In [10]:
R10 = int(input("Enter the number of rows:"))
C10 = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries10 = list(map(float, input().split()))
  
# For printing the matrix
matrix10 = np.array(entries10).reshape(R10, C10)

matrix10i = matrix10**-1

matrix10_inv = np.linalg.inv(matrix10)

print("our matrix, what i found out as its condition number and it's real condition number")

print(matrix10, np.linalg.norm(matrix10)*np.linalg.norm(matrix10i),np.linalg.cond(matrix10), sep = ', ' )

Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
1 4 6 7
our matrix, what i found out as its condition number and it's real condition number
[[1. 4.]
 [6. 7.]], 10.643775927103809, 5.828427124746183


## Tenth Question

In [1]:
pü = np.arange(3)

NameError: name 'np' is not defined

In [21]:
i = 0
i = i + 1
norm = np.sqrt(pü[i]**2 + pü[i]**2 + pü[i]**2)#elle

In [22]:
pü

array([0, 1, 2])

In [23]:
norm


1.7320508075688772

In [24]:
püü = np.linalg.norm(pü) #numpy ile

In [25]:
püü


2.23606797749979

## Eleventh Question

In [15]:
R11 = int(input("Enter the number of rows:"))
C11 = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries11 = list(map(float, input().split()))
  
# For printing the matrix
matrix11 = np.array(entries11).reshape(R11, C11)

def f(matrix11):
    return matrix11[0,0]*(matrix11[1,1]*matrix11[2,2]-matrix11[1,2]*matrix11[2,1]) \
- matrix11[0,1]*(matrix11[1,0]*matrix11[2,2]-matrix11[2,0]*matrix11[1,2]) + \
matrix11[0,2]*(matrix11[1,0]*matrix11[2,1]-matrix11[2,0]*matrix11[1,1])

print("our matrix, what i found as its det, what actually is its det")

print(matrix11, f(matrix11), np.linalg.det(matrix11), sep = ', ')



Enter the number of rows:3
Enter the number of columns:3
Enter the entries in a single line (separated by space): 
2 3 4 5 6 7 3 4 2
our matrix, what i found as its det, what actually is its det
[[2. 3. 4.]
 [5. 6. 7.]
 [3. 4. 2.]], 9.0, 8.999999999999998


## Twelth Question

In [16]:
R12 = int(input("Enter the number of rows:"))
C12 = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries12 = list(map(float, input().split()))
  
# For printing the matrix
matrix12 = np.array(entries12).reshape(R12, C12)

def f(matrix12):
    return np.array([[matrix12[1,1], -matrix12[0,1]],[-matrix12[1,0], matrix12[0,0]]])*1/ \
(matrix12[1,1]*matrix12[0,0] - matrix12[1,0]*matrix12[0,1])

print("our matrix, what i found as its inverse, its actual inverse")

print(matrix12, f(matrix12), np.linalg.inv(matrix12) )

Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
2 3 4 5


## Thirteenth Question

In [ ]:
?

## Fourteenth Question



In [ ]:
#bu soru 9 ile aynı

## Fifteenth Question

Sum of diagonal entries = a_00+ a_11+ a_22+ ...+ a_nn assuming A is an n * n sqaure matrix

In [21]:
R13 = int(input("Enter the number of rows:"))
C13 = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries13 = list(map(float, input().split()))
  
# For printing the matrix
matrix13 = np.array(entries13).reshape(R, C)

Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
2 3 4 5


In [155]:
i = 0
if i == j:
  def f(i):
    return jj[i,i] + jj[i,i]
    
    
#numpy olmadan trace i hesaplamayı denemiştim ama beceremedim

NameError: name 'j' is not defined

In [22]:
a = np.trace(matrix13)

print(a)

7.0


## Sixteenth Question