In [4]:
import numpy as np
#Defining a matrix creation mechanism

#create your first matrix

lst= [ ] 
n = int(input("Enter number of elements : ")) 
  
for i in range(0,n):
    g = [float(input()), float(input())]
    lst.append(g)
      
print(lst)

a = np.array(lst)

#create your second matrix

lst2= [ ] 
n = int(input("Enter number of elements : ")) 
  
for i in range(0,n):
    g = [float(input()), float(input())]
    lst2.append(g)
    
print(lst2)

b = np.array(lst2)


print("Our values:")
print(a, b, np.dot(a, b), sep = '----')

[[2.0, 3.0], [2.0, 3.0]]
[[2.0, 23.0], [2.0, 2.0]]
Our values:
[[2. 3.]
 [2. 3.]]----[[ 2. 23.]
 [ 2.  2.]]----[[10. 52.]
 [10. 52.]]
Their Dot Product:
[[ 4. 69.]
 [ 4.  6.]]


In [6]:
import numpy as np

#An outer product finding mechanism

  
R1 = int(input("Enter the number of rows:"))
C1 = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a single line separated by space
entries1 = list(map(int, input().split()))

matrix1 = np.array(entries1).reshape(R1, C1)

R2 = int(input("Enter the number of rows:"))
C2 = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries2 = list(map(int, input().split()))

matrix2 = np.array(entries2).reshape(R2, C2)
  
# For printing the matrix
print("Our values and their outer product:")

print(matrix1, matrix2, np.outer(matrix, matrix2), sep = ', ')

Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
1 2 3 4
Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
1 2 3 4
Our values and their outer product:
[[1 2]
 [3 4]], [[1 2]
 [3 4]], [[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [7]:
R6 = int(input("Enter the number of rows:"))
C6 = int(input("Enter the number of columns:"))

#A better mechanism for creating matricies
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries6 = list(map(int, input().split()))
  
# For printing the matrix
matrix6 = np.array(entries6).reshape(R6, C6)


R7 = int(input("Enter the number of rows:"))
C7 = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries7 = list(map(int, input().split()))
  
# For printing the matrix
matrix7 = np.array(entries7).reshape(R7, C7)


print(matrix7, matrix6, sep = 'oooooooooo')





Enter the entries in a single line (separated by space): 
Enter the entries in a single line (separated by space): 
[[2 1]
 [4 6]]oooooooooo[[2 3]
 [4 5]]oooooooooo[[ 7 13]
 [26 46]]


In [8]:
import numpy as np

R11 = int(input("Enter the number of rows:"))
C11 = int(input("Enter the number of columns:"))

#A very primitive mechanism for finding determinants
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries11 = list(map(float, input().split()))
  
# For printing the matrix
matrix11 = np.array(entries11).reshape(R11, C11)

def f(matrix11):
    return matrix11[0,0]*(matrix11[1,1]*matrix11[2,2]-matrix11[1,2]*matrix11[2,1]) \
- matrix11[0,1]*(matrix11[1,0]*matrix11[2,2]-matrix11[2,0]*matrix11[1,2]) + \
matrix11[0,2]*(matrix11[1,0]*matrix11[2,1]-matrix11[2,0]*matrix11[1,1])

print("our matrix, what i found as its det, what actually is its det")

print(matrix11, f(matrix11), np.linalg.det(matrix11), sep = ', ')



Enter the entries in a single line (separated by space): 
our matrix, what i found as its det, what actually is its det
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], 0.0, -9.51619735392994e-16


In [16]:
R12 = int(input("Enter the number of rows:"))
C12 = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries12 = list(map(float, input().split()))
  
# For printing the matrix
matrix12 = np.array(entries12).reshape(R12, C12)

def f(matrix12):
    return np.array([[matrix12[1,1], -matrix12[0,1]],[-matrix12[1,0], matrix12[0,0]]])*1/ \
(matrix12[1,1]*matrix12[0,0] - matrix12[1,0]*matrix12[0,1])

print("our matrix, what i found as its inverse, its actual inverse")

print(matrix12, f(matrix12), np.linalg.inv(matrix12) )

Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
2 3 4 5


In [9]:
#matrix multiplication algorithm

def MatMul(X,Y):

   total = np.zeros([np.shape(X)[0], np.shape(Y)[1]])
   a = np.zeros([np.shape(X)[0], np.shape(Y)[1]])

   if np.shape(X)[1] != np.shape(Y)[0]:
      exit(print('your dimensions are incorrect.'))
   else:
      for i in range(len(X)):
         for j in range(len(Y[0])):
            total = 0
            for k in range(len(X[0])):
               total += X[i][k] * Y[k][j]
            a[i][j] = total

      return a

In [12]:
X= np.array([[2,4],[4,5]])
Y= np.array([[6,8],[7,23]])

result= MatMul(X,Y)
kontrol = np.matmul(X,Y)


#print(result, '\n\n', kontrol)
print(result, kontrol, sep = '\n\n\n')

[[ 40. 108.]
 [ 59. 147.]]


[[ 40 108]
 [ 59 147]]


In [14]:
X= np.array([[2,4]])
Y= np.array([[6,8],[7,23],[0,0]])

result= MatMul(X,Y)


#print(result, '\n\n', kontrol)
print(result, sep = '\n\n')

your dimensions are incorrect.
None


: 